// socialv-main/bs5/code-react/src/views/dashboard/ui-kit/ui-tooltips.js
import React from 'react'
import {Container, Row, Col, Card, Button, OverlayTrigger, Tooltip} from 'react-bootstrap'
import {Link} from 'react-router-dom'

const UiTooltips = () => {
    return (
        <>
            <Container>
                <Row>
                    <Col sm="12">
                    <Card className="position-relative inner-page-bg bg-primary" style={{height: "150px"}}>
                        <div className="inner-page-title">
                            <h3 className="text-white">Tooltips Page</h3>
                            <p className="text-white">lorem ipsum</p>
                        </div>
                    </Card>
                    </Col>
                    <Col sm="12" lg="6">
                        <Card>
                            <Card.Header className="d-flex justify-content-between">
                                <div className="header-title">
                                    <h4 className="card-title">Tooltips</h4>
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <p>You can pass the<code> Overlay</code> injected props directly to the Tooltip component. Or pass a Tooltip element to <code> OverlayTrigger </code> instead.</p>
                                <OverlayTrigger placement="top" overlay={
                                    <Tooltip >
                                        Tooltip on top
                                    </Tooltip>
                                    }>
                                    <Button variant="secondary mt-2">Tooltip on top</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="right" overlay={
                                    <Tooltip >
                                        Tooltip on right
                                    </Tooltip>
                                    }>
                                    <Button variant="secondary mt-2">Tooltip on right</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="bottom" overlay={
                                    <Tooltip >
                                        Tooltip on bottom
                                    </Tooltip>
                                    }>
                                    <Button variant="secondary mt-2">Tooltip on bottom</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="left" overlay={
                                    <Tooltip >
                                        Tooltip on left
                                    </Tooltip>
                                    }>
                                    <Button variant="secondary mt-2">Tooltip on left</Button>
                                </OverlayTrigger>{' '}
                            </Card.Body>
                        </Card>
                        <Card>
                            <Card.Header className="d-flex justify-content-between">
                                <div className="header-title">
                                    <h4 className="card-title">Disabled elements</h4>
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <p>Elements with the <code>disabled</code> attribute aren’t interactive, meaning users cannot hover or click them to trigger a popover (or tooltip). As a workaround, you’ll want to trigger the overlay from a wrapper<code> &lt;div&gt; </code>or <code> &lt;span&gt; </code>and override the pointer-events on the disabled element.</p>
                                <OverlayTrigger overlay={<Tooltip id="Disabledtooltip">Disabled tooltip</Tooltip>}>
                                    <span className="d-inline-block">
                                        <Button className="btn-primary" disabled style={{ pointerEvents: 'none' }}>
                                        Disabled button
                                        </Button>
                                    </span>
                                </OverlayTrigger>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col sm="12" lg="6">
                        <Card>
                            <Card.Header className="d-flex justify-content-between">
                                <div className="header-title">
                                    <h4 className="card-title">Tooltips</h4>
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <p>Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left Using background colors</p>
                                <OverlayTrigger placement="top" overlay={
                                    <Tooltip >
                                        Tooltip on top
                                    </Tooltip>
                                    }>
                                    <Button className="btn-primary mt-2">Tooltip on top</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="right" overlay={
                                    <Tooltip >
                                        Tooltip on right
                                    </Tooltip>
                                    }>
                                    <Button className="btn-success mt-2">Tooltip on right</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="bottom" overlay={
                                    <Tooltip >
                                        Tooltip on bottom
                                    </Tooltip>
                                    }>
                                    <Button className="btn-danger mt-2">Tooltip on bottom</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="left" overlay={
                                    <Tooltip >
                                        Tooltip on left
                                    </Tooltip>
                                    }>
                                    <Button className="btn-info mt-2">Tooltip on left</Button>
                                </OverlayTrigger>{' '}
                            </Card.Body>
                        </Card>
                        <Card>
                            <Card.Header className="d-flex justify-content-between">
                                <div className="header-title">
                                    <h4 className="card-title">Tooltips</h4>
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <p>Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left Using Light background colors</p>
                                <OverlayTrigger placement="top" overlay={
                                    <Tooltip >
                                        Tooltip on top
                                    </Tooltip>
                                    }>
                                    <Button className="bg-soft-primary mt-3">Tooltip on top</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="right" overlay={
                                    <Tooltip >
                                        Tooltip on right
                                    </Tooltip>
                                    }>
                                    <Button className="bg-soft-success mt-3">Tooltip on right</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="bottom" overlay={
                                    <Tooltip >
                                        Tooltip on bottom
                                    </Tooltip>
                                    }>
                                    <Button className="bg-soft-danger mt-3">Tooltip on bottom</Button>
                                </OverlayTrigger>{' '}
                                <OverlayTrigger  placement="left" overlay={
                                    <Tooltip >
                                        Tooltip on left
                                    </Tooltip>
                                    }>
                                    <Button className="bg-soft-info mt-3">Tooltip on left</Button>
                                </OverlayTrigger>{' '}
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col lg="12">
                        <Card>
                            <Card.Header className="d-flex justify-content-between">
                                <div className="header-title">
                                    <h4 className="card-title">Hover elements</h4>
                                </div>
                            </Card.Header>
                            <Card.Body>
                                <p>Hover over the buttons below to see the tooltip.</p>
                                <OverlayTrigger overlay={<Tooltip id="tooltip-disabled">Some tooltip text!</Tooltip>}>
                                    <Link to="#" data-bs-toggle="tooltip" title="Some tooltip text!">Hover over me</Link>
                                </OverlayTrigger>
                            </Card.Body>
                        </Card>
                    </Col>
                </Row>
            </Container>   
        </>
    )
}

export default UiTooltips

// socialv-main/bs5/code-vue/src/views/core/UiTooltips.vue
<template>
    <div class="row">
      <div class="col-sm-12">
          <div class="card position-relative inner-page-bg bg-primary" style="height: 150px;">
            <div class="inner-page-title">
                <h3 class="text-white">Tooltips Page</h3>
                <p class="text-white">lorem ipsum</p>
            </div>
          </div>
      </div>
      <div class="col-lg-6 col-sm-12">
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">Tooltips</h4>
          </template>
          <template v-slot:headerAction>
            <a class="text-primary float-right"  role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left. The data-placement attribute specifies the tooltip position.</p>
            <!-- Coming Soon -->
            <tooltip className="btn btn-secondary mt-3 me-1" tooltipPlacement="top" data-bs-original-title="Tooltip on top">Tooltip on top</tooltip>
            <tooltip className="btn btn-secondary mt-3 me-1" tooltipPlacement="right" data-bs-original-title="Tooltip on right">Tooltip on right</tooltip>
            <tooltip className="btn btn-secondary mt-3 me-1" tooltipPlacement="bottom" data-bs-original-title="Tooltip on bottom">Tooltip on bottom</tooltip>
            <tooltip className="btn btn-secondary mt-3 me-1" tooltipPlacement="left" data-bs-original-title="Tooltip on left">Tooltip on left</tooltip>
          </template>
        </iq-card>
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">Disabled elements</h4>
          </template>
          <template v-slot:headerAction>
            <a class="text-primary float-right"  role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Elements with the <code>disabled</code> attribute aren’t interactive, meaning users cannot focus, hover, or click them to trigger a tooltip (or popover). As a workaround, you’ll want to trigger the tooltip from a wrapper <code>&lt;div&gt;</code> or <code>&lt;span&gt;</code>, ideally made keyboard-focusable using <code>tabindex="0"</code>, and override the <code>pointer-events</code> on the disabled element.</p>
            <span class="d-inline-block" tabindex="0"  title="Disabled tooltip">
              <tooltip className="btn btn-primary mt-3"  data-bs-original-title="Tooltip on left" Disabled>Disabled button</tooltip>
            </span>
          </template>
        </iq-card>
      </div>
      <div class="col-lg-6 col-sm-12">
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">Tooltips</h4>
          </template>
          <template v-slot:headerAction>
            <a class="text-primary float-right"  role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left Using background colors</p>
            <tooltip className="btn btn-primary mt-3 me-1" tooltipPlacement="top" data-bs-original-title="Tooltip on top">Tooltip on top</tooltip>
            <tooltip className="btn btn-success mt-3 me-1" tooltipPlacement="right" data-bs-original-title="Tooltip on right">Tooltip on right</tooltip>
            <tooltip className="btn btn-danger mt-3 me-1" tooltipPlacement="bottom" data-bs-original-title="Tooltip on bottom">Tooltip on bottom</tooltip>
            <tooltip className="btn btn-info mt-3 me-1" tooltipPlacement="left" data-bs-original-title="Tooltip on left">Tooltip on left</tooltip>
          </template>
        </iq-card>
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">Tooltips</h4>
          </template>
          <template v-slot:headerAction>
            <a class="text-primary float-right"  role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left Using Light background colors</p>
            <tooltip className="btn btn-soft-primary mt-3 me-1" tooltipPlacement="top" data-bs-original-title="Tooltip on top">Tooltip on top</tooltip>
            <tooltip className="btn btn-soft-success mt-3 me-1" tooltipPlacement="right" data-bs-original-title="Tooltip on right">Tooltip on right</tooltip>
            <tooltip className="btn btn-soft-danger mt-3 me-1" tooltipPlacement="bottom" data-bs-original-title="Tooltip on bottom">Tooltip on bottom</tooltip>
            <tooltip className="btn btn-soft-info mt-3 me-1" tooltipPlacement="left" data-bs-original-title="Tooltip on left">Tooltip on left</tooltip>
          </template>
        </iq-card>
      </div>
      <div class="col-lg-12">
        <iq-card>
          <template v-slot:headerTitle>
            <h4 class="card-title">Hover elements</h4>
          </template>
          <template v-slot:headerAction>
            <a class="text-primary float-right"  role="button">
              <i class="ri-code-s-slash-line" />
            </a>
          </template>
          <template v-slot:body>
            <p>Hover over the buttons below to see the tooltip.</p>
            <tooltip tag="a" href="#" data-bs-toggle="tooltip" title="Tooltip on left">Hover over me</tooltip>
          </template>
        </iq-card>
      </div>
    </div>
</template>
<script>
// import { socialvue } from '../../config/pluginInit'

export default {
  name: 'UiTooltips',
  mounted () {
    // socialvue.index()
  }
}
</script>
