// socialv-main/bs5/code-react/src/views/dashboard/errors/error404.js
import React from 'react'
import {Container, Row, Col, Button, Image} from 'react-bootstrap'
import { useHistory } from 'react-router-dom'

// img
import error404 from '../../../assets/images/error/400.png'

const Error404 = () => {
   let history =useHistory()
    return (
        <>
           <Container className="p-0">
                <Row className="no-gutters height-self-center">
                    <Col sm="12" className="text-center align-self-center">
                        <div className="iq-error position-relative mt-5">
                            <Image src={error404} className="img-fluid iq-error-img" alt=""/>
                            <h2 className="mb-0 text-center">Oops! This Page is Not Found.</h2>
                            <p className="text-center">The requested page dose not exist.</p>
                            <Button variant="primary" className="mt-3" onClick={() => history.push('/')}><i className="ri-home-4-line me-1"></i>Back to Home</Button>                            
                        </div>
                    </Col>
                </Row>
            </Container>        
        </>
    )
}

export default Error404;

// socialv-main/bs5/code-vue/src/views/Pages/Error404.vue
<template>
  <div class="container-fluid p-0">
    <div class="row no-gutters">
      <div class="col-sm-12 text-center">
        <div class="iq-error position-relative mt-5">
          <img :src="image404" class="img-fluid iq-error-img" alt="404">
          <h2 class="mb-0">Oops! This Page is Not Found.</h2>
          <p>The requested page dose not exist.</p>
          <a href="#" @click="$router.go(-1)" class="btn btn-primary mt-3"><i class="ri-home-4-line"></i>Back to Home</a>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
// import { socialvue } from '../../config/pluginInit'

export default {
  name: 'Error404',
  mounted () {
    // socialvue.index()
    // const body = document.querySelector('body')
    // body.classList.add('iq-bg-primary')
  },
  data () {
    return {
      image404: require('../../assets/images/error/400.png')
    }
  }
}
</script>
