// socialv-main/bs5/code-react/src/views/dashboard/app/friend-request.js
import React from 'react'
import {Row,Col, Container} from 'react-bootstrap'
import Card from '../../../components/Card'
import {Link} from 'react-router-dom'
// img

import user5 from '../../../assets/images/user/05.jpg'
import user6 from '../../../assets/images/user/06.jpg'
import user7 from '../../../assets/images/user/07.jpg'
import user8 from '../../../assets/images/user/08.jpg'
import user9 from '../../../assets/images/user/09.jpg'
import user10 from '../../../assets/images/user/10.jpg'
import user11 from '../../../assets/images/user/11.jpg'
import user12 from '../../../assets/images/user/12.jpg'
import user13 from '../../../assets/images/user/13.jpg'
import user14 from '../../../assets/images/user/14.jpg'
import user15 from '../../../assets/images/user/15.jpg'
import user16 from '../../../assets/images/user/16.jpg'
import user17 from '../../../assets/images/user/17.jpg'
//Sweet alert
import Swal from 'sweetalert2'


const FriendReqest = () => {

const questionAlert = () => {
   const swalWithBootstrapButtons = Swal.mixin({
     customClass: {
       cancelButton: 'btn btn-outline-primary btn-lg ms-2',
       confirmButton: 'btn btn-primary btn-lg',
       
       
     },
     buttonsStyling: false
   })
   
   swalWithBootstrapButtons.fire({
     title: 'Are you sure?',
     text: "You won't be able to revert this!",
     icon: 'warning',
     showCancelButton: true,
     cancelButtonText: 'cancel',
     confirmButtonText: 'Yes, delete it!',
    
     reverseButtons: false,
     showClass: {
      popup: 'animate__animated animate__zoomIn'
  },
  hideClass: {
      popup: 'animate__animated animate__zoomOut'
  }
    
   }).then((result) => {
     if (result.isConfirmed) {
       swalWithBootstrapButtons.fire({
         title: 'Deleted!',
         text: 'Your Request has been deleted.',
         icon: 'success',
         showClass: {
           popup: 'animate__animated animate__zoomIn'
         },
         hideClass: {
           popup: 'animate__animated animate__zoomOut'
         }
       })
     } else if (
       /* Read more about handling dismissals below */
       result.dismiss === Swal.DismissReason.cancel
     ) {
      swalWithBootstrapButtons.fire({
         title: 'Your Request is safe!',
         showClass: {
           popup: 'animate__animated animate__zoomIn'
         },
         hideClass: {
           popup: 'animate__animated animate__zoomOut'
         }
       })
     }
   })
 }
 
   return(
      <>
         <Container>
            <Row>
               <Col sm="12">
                  <Card>
                     <Card.Header className="d-flex justify-content-between">
                        <div className="header-title">
                           <h4 className="card-title">Friend Request</h4>
                        </div>
                     </Card.Header>
                     <Card.Body>
                        <ul className="request-list list-inline m-0 p-0">
                           <li className="d-flex align-items-center  justify-content-between flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user5} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Jaques Amole</h6>
                                 <p className="mb-0">40  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <div className="confirm-click-btn">
                                    <Link to="#" className="me-3 btn btn-primary rounded confirm-btn">Confirm</Link>
                                    <Link to="#" className="me-3 btn btn-primary rounded request-btn" style={{display: "none"}}>View All</Link>
                                 </div>
                                 <Link to="#" onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  justify-content-between flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user6} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Lucy Tania</h6>
                                 <p className="mb-0">12  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">                                    
                                 <div className="confirm-click-btn">
                                    <Link to="#" className="me-3 btn btn-primary rounded confirm-btn">Confirm</Link>
                                    <Link to="#" className="me-3 btn btn-primary rounded request-btn" style={{display: "none"}}>View All</Link>
                                 </div>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user7} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Val Adictorian</h6>
                                 <p className="mb-0">0  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <div className="confirm-click-btn">
                                    <Link to="#" className="me-3 btn btn-primary rounded confirm-btn">Confirm</Link>
                                    <Link to="#" className="me-3 btn btn-primary rounded request-btn" style={{display: "none"}}>View All</Link>
                                 </div>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user8} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Manny Petty</h6>
                                 <p className="mb-0">3  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user9} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Marsha Mello</h6>
                                 <p className="mb-0">15  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user10} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Caire Innet</h6>
                                 <p className="mb-0">8  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user11} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Gio Metric</h6>
                                 <p className="mb-0">10  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user12} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Chris P. Cream</h6>
                                 <p className="mb-0">18  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user13} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Paul Misunday</h6>
                                 <p className="mb-0">6  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user14} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Reanne Carnation</h6>
                                 <p className="mb-0">12  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded">Confirm</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Delete Request</Link>                                    
                              </div>
                           </li>
                           <li className="d-block text-center mb-0 pb-0">
                              <Link to="#" className="me-3 btn">View More Request</Link>
                           </li>
                        </ul>
                     </Card.Body>
                  </Card>
                  <Card>
                     <Card.Header className="d-flex justify-content-between">
                        <div className="header-title">
                           <h4 className="card-title">People You May Know</h4>
                        </div>
                     </Card.Header>
                     <Card.Body>
                        <ul className="request-list m-0 p-0">
                           <li className="d-flex align-items-center  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user15} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Jen Youfelct</h6>
                                 <p className="mb-0">4  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user16} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Cooke Edoh</h6>
                                 <p className="mb-0">20  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                    <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user17} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Earl E. Riser</h6>
                                 <p className="mb-0">30  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                    <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user5} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Cliff Diver</h6>
                                 <p className="mb-0">5  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user6} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Cliff Diver</h6>
                                 <p className="mb-0">5  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user7} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Vinny Gret</h6>
                                 <p className="mb-0">50  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user8} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Paul Samic</h6>
                                 <p className="mb-0">6  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user9} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Gustav Wind</h6>
                                 <p className="mb-0">14  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                    <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user10} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Minnie Strone</h6>
                                 <p className="mb-0">16  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                    <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user11} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Ray Volver</h6>
                                 <p className="mb-0">9  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user12} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Indy Nile</h6>
                                 <p className="mb-0">6  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                           <li className="d-flex align-items-center mb-0 pb-0  flex-wrap">
                              <div className="user-img img-fluid flex-shrink-0">
                                 <img src={user13} alt="story-img" className="rounded-circle avatar-40"/>
                              </div>
                              <div className="flex-grow-1 ms-3">
                                 <h6>Jen Trification</h6>
                                 <p className="mb-0">42  friends</p>
                              </div>
                              <div className="d-flex align-items-center mt-2 mt-md-0">
                                 <Link to="#" className="me-3 btn btn-primary rounded"><i className="ri-user-add-line me-1"></i>Add Friend</Link>
                                 <Link to="#"  onClick={questionAlert} className="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item">Remove</Link>                                    
                              </div>
                           </li>
                        </ul>
                     </Card.Body>
                  </Card>
               </Col>
            </Row>
         </Container>
      </>
   )
}

export default FriendReqest

// socialv-main/bs5/code-vue/src/views/SocailMain/Friends/FriendRequest.vue
<template>
  <div class="row">
    <div class="col-sm-12" v-for="(item,index) in friendRequest" :key="index">
        <iq-card>
          <template v-slot:headerTitle>
                <h4 class="card-title">{{item.title}}</h4>
          </template>
          <template v-slot:body>
              <ul class="request-list list-inline m-0 p-0">
                <li class="d-flex align-items-center  justify-content-between flex-wrap" v-for="(list,index1) in item.list" :key="index1">
                    <div class="user-img img-fluid flex-shrink-0">
                      <img :src="list.img" alt="story-img" class="rounded-circle avatar-40">
                    </div>
                    <div class="flex-grow-1 ms-3">
                      <h6>{{list.name}}</h6>
                      <p class="mb-0">{{list.friend}}</p>
                    </div>
                    <div class="d-flex align-items-center mt-2 mt-md-0">
                      <div class="confirm-click-btn">
                          <a href="#" class="me-3 btn btn-primary rounded confirm-btn"><i class="ri-user-add-line me-1"></i>{{item.btn1}}</a>
                          <a href="@/app/profile.html" class="me-3 btn btn-primary rounded request-btn" style="display: none;"></a>
                      </div>
                      <a href="#" class="btn btn-secondary rounded" data-extra-toggle="delete" data-closest-elem=".item" @click="deleterequest">{{item.btn2}}</a>
                    </div>
                </li>
                <li class="d-block text-center mb-0 pb-0"  v-if="item.title == 'Friend Request'">
                    <a href="#" class="me-3 btn">View More Request</a>
                </li>
              </ul>
          </template>
        </iq-card>
    </div>
  </div>
</template>
<script>
import { socialvue } from '../../../config/pluginInit'
export default {
  name: 'FriendRequest',
  mounted () {
    socialvue.index()
  },
  data () {
    return {
      friendRequest: [
        {
          title: 'Friend Request',
          btn1: 'Confirm',
          btn2: 'Delete Request',
          list: [
            {
              img: require('../../../assets/images/user/05.jpg'),
              name: 'Jaques Amole',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/06.jpg'),
              name: 'Lucy Tania',
              friend: '12  friends'
            },
            {
              img: require('../../../assets/images/user/07.jpg'),
              name: 'Val Adictorian',
              friend: '0  friends'
            },
            {
              img: require('../../../assets/images/user/08.jpg'),
              name: 'Manny Petty',
              friend: '3  friends'
            },
            {
              img: require('../../../assets/images/user/09.jpg'),
              name: 'Marsha Mello',
              friend: '15  friends'
            },
            {
              img: require('../../../assets/images/user/10.jpg'),
              name: 'Caire Innet',
              friend: '8  friends'
            },
            {
              img: require('../../../assets/images/user/11.jpg'),
              name: 'Gio Metric',
              friend: '10  friends'
            },
            {
              img: require('../../../assets/images/user/12.jpg'),
              name: 'Chris P. Cream',
              friend: '18  friends'
            },
            {
              img: require('../../../assets/images/user/05.jpg'),
              name: 'Paul Misunday',
              friend: '6  friends'
            },
            {
              img: require('../../../assets/images/user/13.jpg'),
              name: 'Reanne Carnation',
              friend: '12  friends'
            }
          ]

        },
        {
          title: 'People You May Know',
          btn1: 'Add Friend',
          btn2: 'Remove',
          list: [
            {
              img: require('../../../assets/images/user/14.jpg'),
              name: 'Jen Youfelct',
              friend: '4 friends'
            },
            {
              img: require('../../../assets/images/user/15.jpg'),
              name: 'Jen Youfelct',
              friend: '20  friends'
            },
            {
              img: require('../../../assets/images/user/16.jpg'),
              name: 'Jaques Amole',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/17.jpg'),
              name: 'Earl E. Riser',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/18.jpg'),
              name: 'Cliff Diver',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/19.jpg'),
              name: 'Cliff Diver',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/05.jpg'),
              name: 'Joyce Tick',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/18.jpg'),
              name: 'Vinny Gret',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/06.jpg'),
              name: 'Paul Samic',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/07.jpg'),
              name: 'Gustav Wind',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/05.jpg'),
              name: 'Minnie Strone',
              friend: '40  friends'
            },
            {
              img: require('../../../assets/images/user/04.jpg'),
              name: 'Ray Volver',
              friend: '40  friends'
            }
          ]
        }
      ]
    }
  },
  methods: {
    deleterequest () {
      const swalWithBootstrapButtons = this.$swal.mixin({
        customClass: {
          confirmButton: 'btn btn-primary btn-lg',
          cancelButton: 'btn btn-outline-primary btn-lg ms-2'
        },
        buttonsStyling: false
      })

      swalWithBootstrapButtons.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, delete it!',
        showClass: {
          popup: 'animate__animated animate__zoomIn'
        },
        hideClass: {
          popup: 'animate__animated animate__zoomOut'
        }
      })
        .then((willDelete) => {
          if (willDelete.isConfirmed) {
            swalWithBootstrapButtons.fire({
              title: 'Deleted!',
              text: 'Your Request has been deleted.',
              icon: 'success',
              showClass: {
                popup: 'animate__animated animate__zoomIn'
              },
              hideClass: {
                popup: 'animate__animated animate__zoomOut'
              }
            })
          } else {
            swalWithBootstrapButtons.fire({
              title: 'Your Request is safe!',
              showClass: {
                popup: 'animate__animated animate__zoomIn'
              },
              hideClass: {
                popup: 'animate__animated animate__zoomOut'
              }
            })
          }
        })
    }
  }
}
</script>
