// socialv-main/bs5/code-vue/src/views/Pages/Pricing1.vue
<template>

<div class="row">
  <div class="col-sm-12">
      <div class="card position-relative inner-page-bg bg-primary" style="height: 150px;">
        <div class="inner-page-title">
            <h3 class="text-white">Pricing1 Page</h3>
            <p class="text-white">lorem ipsum</p>
        </div>
      </div>
  </div>
  <div class="col-lg-3 col-md-6 col-sm-12" v-for="(item,index) in cards" :key="index">
    <div class="card" :class="item.active ? 'bg-primary text-white' : ''">
      <div class="card-body border text-center rounded">
        <span class="text-uppercase" v-if="item.plan !== ''">{{item.plan}}</span>
        <div class="d-flex align-items-center justify-content-center">
          <h2 class="mb-4 display-3" :class="item.active ? 'text-white' : ''">{{item.amount}}</h2>
          <small class=" text-muted" :class="item.active ? 'text-white' : 'text-muted'">{{item.duration}}</small>
        </div>
        <ul class="list-unstyled line-height-4 mb-0">
          <li>{{item.description}}</li>
          <li>{{item.description1}}</li>
          <li>{{item.description2}}</li>
        </ul>
        <a href="#" :class="item.active ? 'btn btn-light text-dark btn-block mt-5' +' '+item.buttonClass : 'btn btn-primary mt-5' +' '+item.buttonClass">{{item.button}}</a>
      </div>
    </div>
  </div>
  <div class="col-lg-3 col-md-6 col-sm-12" v-for="(item,index) in bgCards" :key="item.amount+index">
      <div class="card bg-dark text-white text-center">
        <img :src="item.bgImage" class="card-img rounded" alt="#">
        <div class="card-img-overlay">
            <div class="d-flex align-items-center justify-content-center">
              <h2 class="mb-4 display-3 text-white">{{item.amount}}</h2>
              <small class="text-white">{{item.duration}}</small>
            </div>
            <ul class="list-unstyled line-height-4 mb-0 ">
              <li>{{item.description}}</li>
              <li>{{item.description1}}</li>
              <li>{{item.description2}}</li>
            </ul>
            <button type="button" class="btn btn-primary mt-3">{{item.button}}</button>
        </div>
      </div>
  </div>
</div>

</template>
<script>
// import { socialvue } from '../../config/pluginInit'

export default {
  name: 'Pricing1',
  mounted () {
    // socialvue.index()
  },
  data () {
    return {
      cards: [
        {
          plan: 'Basic',
          amount: '$26',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Start Starter',
          buttonClass: '',
          bgImage: false
        },
        {
          plan: 'Basic',
          amount: '$99',
          duration: '/ Month',
          active: true,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Start Starter',
          buttonClass: 'btn-block',
          bgImage: false
        },
        {
          plan: 'Basic',
          amount: '$39',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Start Starter',
          buttonClass: '',
          bgImage: false
        },
        {
          plan: 'Basic',
          amount: '$25',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Start Starter',
          buttonClass: '',
          bgImage: false
        }
      ],
      bgCards: [
        {
          amount: '$19',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Get Started',
          buttonClass: '',
          bgImage: require('@/assets/images/page-img/25.jpg')
        },
        {
          amount: '$19',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Get Started',
          buttonClass: '',
          bgImage: require('@/assets/images/page-img/26.jpg')
        },
        {
          amount: '$19',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Get Started',
          buttonClass: '',
          bgImage: require('@/assets/images/page-img/27.jpg')
        },
        {
          amount: '$19',
          duration: '/ Month',
          active: false,
          description: 'Lorem ipsum dolor sit amet',
          description1: 'Consectetur adipiscing elit',
          description2: 'Integer molestie lorem at massa',
          button: 'Get Started',
          buttonClass: '',
          bgImage: require('@/assets/images/page-img/28.jpg')
        }
      ]
    }
  }
}
</script>

// socialv-main/bs5/code-react/src/views/dashboard/extrapages/pricing1.js
import React from 'react'
import {Card, Container, Row, Col, Button, Image} from 'react-bootstrap'

//image
import image25 from '../../../assets/images/page-img/25.jpg'
import image26 from '../../../assets/images/page-img/26.jpg'
import image27 from '../../../assets/images/page-img/27.jpg'
import image28 from '../../../assets/images/page-img/28.jpg'

const Pricing1 = () => {
    return (
        <>
            <Container>
                <Row>
                    <Col sm="12">
                        <Card className="position-relative inner-page-bg bg-primary" style={{height: "150px"}}>
                            <div className="inner-page-title">
                                <h3 className="text-white">Pricing-1 Page</h3>
                                <p className="text-white">lorem ipsum</p>
                            </div>
                        </Card>
                    </Col>
                    <Col lg="3" md="6" sm="12">
                        <Card>
                            <Card.Body className="border text-center rounded">
                                <span className="text-uppercase">Basic</span>
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3">$26</h2>                         
                                    <small className=" text-muted">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button className="btn-primary mt-5">Start Starter</Button>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col lg="3" md="6" sm="12">
                        <Card className="bg-primary text-white">
                            <Card.Body className="border text-center rounded">
                                <span className="text-uppercase">Basic</span>
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3 text-white">$99</h2>                         
                                    <small className="text-white-50">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0 ">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button  className="btn-light text-dark btn-block mt-5">Start Starter</Button>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col lg="3" md="6" sm="12">
                        <Card>
                            <Card.Body className="border text-center rounded">
                                <span className="text-uppercase">Basic</span>
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3">$39</h2>                         
                                    <small className=" text-muted">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button className="btn-primary mt-5">Start Starter</Button>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col lg="3" md="6" sm="12">
                        <Card>
                            <Card.Body className="border text-center rounded">
                                <span className="text-uppercase">Basic</span>
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3">$25</h2>                         
                                    <small className=" text-muted">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button className="btn-primary mt-5">Start Starter</Button>
                            </Card.Body>
                        </Card>
                    </Col>
                    <Col lg="3">
                        <Card className="bg-dark text-white text-center">
                            <Image src={image25} className="card-img rounded" alt="#"/>
                            <div className="card-img-overlay">
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3 text-white">$19</h2>                         
                                    <small className="text-white">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0 ">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button className="btn-primary mt-3">Get started</Button>
                            </div>
                        </Card>
                    </Col>
                    <Col lg="3">
                        <Card className="bg-dark text-white text-center">
                            <Image src={image26} className="card-img rounded" alt="#"/>
                            <div className="card-img-overlay">
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3 text-white">$19</h2>                         
                                    <small className="text-white">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button variant="primary" className="mt-3">Get started</Button>
                            </div>
                        </Card>
                    </Col>
                    <Col lg="3">
                        <Card className="bg-dark text-white text-center">
                            <Image src={image27} className="card-img rounded" alt="#"/>
                            <div className="card-img-overlay">
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3 text-white">$19</h2>                         
                                    <small className="text-white">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0 ">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button variant="primary" className="mt-3">Get started</Button>
                            </div>
                        </Card>
                    </Col>
                    <Col lg="3">
                        <Card className="bg-dark text-white text-center">
                            <Image src={image28} className="card-img rounded" alt="#"/>
                            <div className="card-img-overlay">
                                <div className="d-flex align-items-center justify-content-center">
                                    <h2 className="mb-4 display-3 text-white">$19</h2>                         
                                    <small className="text-white">/ Month</small>
                                </div> 
                                <ul className="list-unstyled line-height-4 mb-0 ">
                                    <li>Lorem ipsum dolor sit amet</li>
                                    <li>Consectetur adipiscing elit</li>
                                    <li>Integer molestie lorem at massa</li>
                                </ul>
                                <Button variant="primary" className="mt-3">Get started</Button>
                            </div>
                        </Card>
                    </Col>
                </Row>
            </Container>
        </>
    )
}

export default Pricing1
